# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory-management:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "PG_EXTERNAL_URL"
