# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog:$VERSION
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=PG_EXTERNAL_URL
    restart: "no"

  inventory-management:
    image: inventory-management:$VERSION
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=PG_EXTERNAL_URL
    restart: "no"
